### ISSUE TITLE
Update Code To Python 3 and GTK3 

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/mintmenu#161]
@clefebvre @mtwebster I know that this is on you guys' TODO list, but I'm wondering if you already have specific plans as to the how/what/when/who? If there aren't any plans yet I'd be happy to start working on it. I'm not sure exactly how quickly I can get it done by myself considering my current work schedule but I could open a PR to track my progress and also make it easier for others to jump in and contribute if they want to. Please let me know your thoughts. Cheers!

Related: #133

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/mintmenu/pull/162

**Comment by clefebvre** [comment]
Thansk @lots0logs. @leigh123linux already did it. The reason it's not being merged yet is because there's a tight bond between applets and MATE libs and we're still using GTK+ in MATE at the moment.

As we get closer to Mint 18.1 I'm hoping we'll get to ship MATE 1.16 in GTK3 and we'll then be able to switch mintmenu.
