### ISSUE TITLE
MintMenu doesn't work

### ISSUE THREAD

**Issue by dimitrispapan** [linuxmint/mintmenu#249]
Hi there, 
I have used Mint cinammon 19.3 for a couple of days. Everything was fine. I opened my laptop once and the menu button was gone, I tried to launc the MintMenu app frop the software center and no response came up. I also removed and reinstalled the app and nothing changed. 
Please I need help I can't use my laptop without menu.

**Comment by xenopeek** [comment]
For help with troubleshooting this would be better asked on the support forums; this isn't something a developer can do anything with. We have a forum for Cinnamon issues here: https://forums.linuxmint.com/viewforum.php?f=208. You'll need to register an account to make a new topic. If it turns out it''s a bug in a Linux Mint component this issue here can be reopened.

mintMenu won't work on Cinnamon as it's for MATE. Cinnamon has its own menu applet, included with Cinnamon. If your panel is misbehaving try right-clicking the panel, unfold Troubleshoot in the context menu and select Restore all settings to default.
