### ISSUE TITLE
Mintmenu should also search the "Exec"-String

### ISSUE THREAD

**Issue by spectas** [linuxmint/mintmenu#48]
Hello everybody,

right now Mintmenu ignores the name of the executable file (e.g. acroread) when typing in a command in the Mint Menu. I would like Mintmenu to include the executable file's names in the search process and put more relevance to the result than the other strings.

Technically, I think, that Mintmenu right now looks into the string "Name=" of the *.desktop-file (/usr/share/applications), but ignores its "Exec=" string. Additionally it seems to me, that Mintmenu also searches the file name of the *.desktop-file itself.

Some examples:
1. "Adobe Reader":
   When typing "acroread" (the executable file name), nothing is displayed. Whereas you can input "adobe reader" (which is the Name-string in the desktop file) or "adobereader" (which is the name of the desktop-file itself), to have a result.
2. "Newsreader Pan"
   There is a newsreader which is called Pan. When you type in "pan", Mintmenu shows 9 results, number 8 is "Newsreader Pan". Mintmenu should also read the executable name "pan", and put more relevance to the result, as the executable name is imho the most important one.
3. "Language Support"
   When typing "gnome-language-selector" (executable's name), Mintmenu displays no result, but does it when typing "language-selector" (desktop file's name). What I don't understand in this case is, that it is not possible neither, to type in "Language Support" (which is written in the "Name=" string).

Kind regards, Spectas

**Comment by xenopeek** [comment]
1 and 3 appear to have been implemented since this issue was posted. Testing on Linux Mint 18.3 MATE, if I for example search for driver-manager or timeshift-launcher (the commands from the Exec string) I find Driver Manager and Timeshift respectively. The .desktop files for these are called mintdrivers.desktop and timeshift-gtk.desktop and so the menu isn't searching the .desktop filenames but the Name and Exec strings within.

I can't reproduce 2 as when I install pan and search for pan in the menu, the only result is Pan Newsreader.
